#!/usr/bin/env bash 
# a Bash script that displays Best School 10 times 
count=1 
while [ $count -lt 11 ] 
do 
    if [ $count -eq 9 ] 
    then 
        echo "Best School" 
        echo "Hi" 
    else 
        echo "Best School" 
    fi 
    ((count++)) 
done
