#!/usr/bin/env bash 
#A Bash script that loops from 1 to 10 and:displays bad luck for the 4th loop iteration,displays good luck for the 8th loop iteration,displays Best School for the other iterations
A=0 
while [ $A -le 9 ] 
do 
    if [ $A -eq 3 ] 
    then 
        echo "bad luck" 
    elif [ $A -eq 7 ] 
    then 
        echo "good luck" 
    else 
        echo "Best School" 
    fi 
    ((A++)) 
done
